version: '3'
services:
  sftp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 2222:22
    container_name: sftp-container
    volumes:
    - /home/lucio/sftp-test/sftp_key:/etc/ssh/authorized_keys/sftpuser.pub
    - ./inbound:/home/sftpuser/inbound
    - ./inbound:/inbound
    - ./outbound:/outbound
    - ./outbound:/home/sftpuser/outbound
